"""minor bug fix

Revision ID: 1a0ffc9c0b0b
Revises: 7c41b4a83985
Create Date: 2024-01-06 15:23:26.952093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0ffc9c0b0b'
down_revision: Union[str, None] = '7c41b4a83985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'course_id')
    # ### end Alembic commands ###
