"""empty message

Revision ID: 42e7a693faf7
Revises: 9424d97f8bbe
Create Date: 2024-03-13 13:29:04.781910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e7a693faf7'
down_revision: Union[str, None] = '9424d97f8bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('instructors', sa.String(), nullable=True))
    op.add_column('course', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('course', sa.Column('prerequisites', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'prerequisites')
    op.drop_column('course', 'duration')
    op.drop_column('course', 'instructors')
    # ### end Alembic commands ###
