"""added Questions and topics

Revision ID: 7c41b4a83985
Revises: c8d09f11c86e
Create Date: 2024-01-06 14:58:55.517790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c41b4a83985'
down_revision: Union[str, None] = 'c8d09f11c86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('question_uri', sa.String(), nullable=True),
    sa.Column('option_a', sa.String(), nullable=True),
    sa.Column('option_b', sa.String(), nullable=True),
    sa.Column('option_c', sa.String(), nullable=True),
    sa.Column('option_d', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_uri', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_a'),
    sa.UniqueConstraint('option_b'),
    sa.UniqueConstraint('option_c'),
    sa.UniqueConstraint('option_d')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('topics')
    # ### end Alembic commands ###
