"""fixed seleted

Revision ID: 99192c0f1b83
Revises: c090a8e7f871
Create Date: 2024-01-08 18:49:45.398188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99192c0f1b83'
down_revision: Union[str, None] = 'c090a8e7f871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('results', 'seleted_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('seleted_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('results', 'selected_options')
    # ### end Alembic commands ###
