"""added test table

Revision ID: b24e647a8bc7
Revises: 99192c0f1b83
Create Date: 2024-01-09 21:02:21.343033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24e647a8bc7'
down_revision: Union[str, None] = '99192c0f1b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_questions_association',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], )
    )
    op.add_column('results', sa.Column('test_id', sa.Integer(), nullable=False))
    op.alter_column('results', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint('results_topic_id_fkey', 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'test', ['test_id'], ['id'])
    op.drop_column('results', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key('results_topic_id_fkey', 'results', 'topics', ['topic_id'], ['id'])
    op.alter_column('results', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('results', 'test_id')
    op.drop_table('test_questions_association')
    op.drop_table('test')
    # ### end Alembic commands ###
