"""empty message

Revision ID: c80a579c3c72
Revises: 42e7a693faf7
Create Date: 2024-03-13 19:10:39.316013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80a579c3c72'
down_revision: Union[str, None] = '42e7a693faf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE course ALTER COLUMN duration TYPE INTEGER USING duration::integer")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE course ALTER COLUMN duration TYPE VARCHAR USING duration::varchar")
    # ### end Alembic commands ###
